mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: ASSIGN_ID
spring:
  main:
    allow-circular-references: true
springdoc:
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: /user/**,/addressBook/**
      packages-to-scan: org.example.reggie.user.controller,
  swagger-ui:
    enabled: true
knife4j:
  enable: true
  setting:
    language: zh_cn
