server:
  port: 9090
spring:
  application:
    name: reggie_take_out
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
  mvc:
    servlet:
      load-on-startup: 1
logging:
  level:
    root: info
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: ASSIGN_ID
