server:
  port: 9090
spring:
  application:
    name: reggie_take_out
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
  mvc:
    servlet:
      load-on-startup: 1
logging:
  level:
    root: info
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: ASSIGN_ID
knife4j:
  enable: true
  openapi:
    title: 瑞吉外卖
    description: "瑞吉外卖项目接口文档"
    concat: gongshuiwen
    email: gongshuiwen@gmail.com
    version: v1.0.0
    group:
      default:
        group-name: default
        api-rule: package
        api-rule-resources:
          - org.example.reggie
