server:
  port: 9090
spring:
  application:
    name: reggie_take_out
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
  mvc:
    servlet:
      load-on-startup: 1
  redis:
    host: 127.0.0.1
    database: 0
    port: 6379
    password:
    timeout: 1000ms
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1ms
logging:
  level:
    root: info
reggie:
  base-path: data/
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: ASSIGN_ID
