spring:
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:shardingsphere-jdbc.yml
  redis:
    host: 127.0.0.1
    database: 0
    port: 6379
    password:
    timeout: 1000ms
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1ms
minio:
  endpoint: http://127.0.0.1:9000
  access-key: IAe5GIJVpAHuBhz9s2DT
  secret_key: CselVVxGr6wZTEgTuX5PYKDXlXO9iHkn1IbbduT3
  bucket-name: reggie
