spring:
  cloud:
    gateway:
      routes:
        - id: reggie-backend
          uri: lb://reggie-backend
          predicates:
            - Path=/addressBook/**,/category/**,/common/**,/dish/**,/employee/**,/order/**,/setmeal/**,/shoppingCart/**,/user/**
