server:
  port: 8080
spring:
  application:
    name: reggie-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.88.243:8848
    gateway:
      routes:
        - id: reggie-backend
          uri: lb://reggie-backend
          predicates:
            - Path=/addressBook/**,/category/**,/common/**,/dish/**,/employee/**,/order/**,/setmeal/**,/shoppingCart/**,/user/**
