spring:
  cloud:
    gateway:
      routes:
        - id: reggie-backend
          uri: lb://reggie-backend
          predicates:
            - Path=/category/**,/common/**,/dish/**,/employee/**,/order/**,/setmeal/**,/shoppingCart/**,/user/login/**
        - id: reggie-user
          uri: lb://reggie-user
          predicates:
            - Path=/addressBook/**,/user/**
